// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Item } from "./Item";
import type { OrdItem } from "./OrdItem";

export type Folder = { item: Item, path_param: string, base_nm: string, tot?: number, cnt?: number, skip_n?: number, take_n?: number, ordering?: Array<OrdItem>, };
