// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { nm: string, dir: boolean, ext?: string, mt?: string, sz?: bigint, cnt?: number, has?: boolean, tm?: bigint, items?: Array<Item>, };
