// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Item = { name: string, is_dir: boolean, ext?: string, mime?: string, size?: bigint, cnt?: number, has_items?: boolean, tm?: bigint, items?: Array<Item>, };
