// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetaType } from "./MetaType";
import type { OrdItem } from "./OrdItem";

export type OptParams = { path_str?: string, meta_types?: Array<MetaType>, ordering?: Array<OrdItem>, skip_n?: number, take_n?: number, is_pretty?: boolean, cache_nm?: string, };
