// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderAsc } from "./OrderAsc";
import type { OrderBy } from "./OrderBy";

export type OrdItem = { nm: OrderBy, asc: OrderAsc, };
