// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { State } from "./State";

export type StateParams = { key: string, val: State, };
