/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class FolderApi {
  constructor()
  readText(pathStr: string): Promise<string>
  readFolder(jsonParams: string): Promise<string>
  /**
   *
   * set state
   *
   * # arg
   * - key
   * - opt_val: if `None` then delete cache
   *
   * # Examples
   * ```
   * set_stat("key".to_string(), Some("val".to_string())
   * set_state("key".to_string(), None)
   * ```
   */
  setState(key: string, val?: string | undefined | null): Promise<string | null>
  /**
   *
   * get state
   *
   * # arg
   * - key
   * - default_val: If the key does not exist in the cache, insert the default value and return it.
   */
  getState(key: string, defaultVal?: string | undefined | null): Promise<string | null>
  getHomeDir(): Promise<string>
  getDisks(): Promise<string>
}
