/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class FolderApi {
  constructor()
  readFolder(jsonParams: string): Promise<string>
  getState(jsonParams: string): Promise<string>
  setState(jsonParams: string): Promise<string>
}
